name: Python Lint
run-name: Python Lint

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
      - beta

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1